const KEY="questweek.pages.v3",DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const ICON={Gym:"🏋️",Japanese:"🇯🇵",Study:"📚",Work:"💼",Commute:"🚌",Badminton:"🏸",Boxing:"🥊",Endurance:"🏊",Calisthenics:"🤸",Chess:"♟️",Meditation:"🧘",Stretching:"🧎",Sleep:"🌙",Programming:"💻",Income:"💰",Planning:"🗓️",Personal:"•"};
const XP={Gym:100,Japanese:75,Study:60,Programming:60,Income:60,Badminton:80,Boxing:80,Endurance:90,Calisthenics:35,Chess:30,Meditation:15,Stretching:15,Sleep:30,Planning:20,Personal:10,Commute:0,Work:0};
function monday(d=new Date()){d=new Date(d);d.setHours(0,0,0,0);let n=d.getDay();d.setDate(d.getDate()+(n===0?-6:1-n));return d}
function dk(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function wk(){return dk(monday())} function tid(){let n=new Date().getDay();return n===0?6:n-1}
function id(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function tasks(skill="Handstand"){
 let a=[
{d:0,t:"Wake up",tm:"05:30",c:"Sleep"},{d:0,t:"Meditation",tm:"05:30–05:35",c:"Meditation"},{d:0,t:"Quick breakfast and prepare",tm:"05:35–05:45",c:"Personal"},{d:0,t:"Travel to fitness center",tm:"05:45–06:25",c:"Commute",f:1},{d:0,t:"Push · core workout",tm:"06:25–07:25",c:"Gym"},{d:0,t:"Shower and change at gym",tm:"07:25–07:40",c:"Personal",f:1},{d:0,t:"Travel directly to school",tm:"07:40–07:55",c:"Commute",f:1},{d:0,t:"School",tm:"08:15 onward",c:"Study",f:1},{d:0,t:"Study block",tm:"30–45 min before Japanese",c:"Study"},{d:0,t:"Travel to Japanese class",tm:"Before 17:15",c:"Commute",f:1},{d:0,t:"Japanese class",tm:"17:15–19:05",c:"Japanese",f:1},{d:0,t:`${skill} practice`,tm:"10–15 min after class",c:"Calisthenics"},
{d:1,t:"Wake up",tm:"05:30",c:"Sleep"},{d:1,t:"Meditation",tm:"05:30–05:35",c:"Meditation"},{d:1,t:"Quick breakfast and prepare",tm:"05:35–05:45",c:"Personal"},{d:1,t:"Travel to fitness center",tm:"05:45–06:25",c:"Commute",f:1},{d:1,t:"Pull · core workout",tm:"06:25–07:25",c:"Gym"},{d:1,t:"Shower and change at gym",tm:"07:25–07:40",c:"Personal",f:1},{d:1,t:"Travel directly to school",tm:"07:40–07:55",c:"Commute",f:1},{d:1,t:"School",tm:"08:15–15:30",c:"Study",f:1},{d:1,t:"Travel to work",tm:"15:30–16:00",c:"Commute",f:1},{d:1,t:"Work",tm:"16:00–20:00",c:"Work",f:1},{d:1,t:"Travel home",tm:"20:00–21:00",c:"Commute",f:1},{d:1,t:"Dinner and wind-down",tm:"21:00–21:30",c:"Personal"},
{d:2,t:"Wake up",tm:"05:30",c:"Sleep"},{d:2,t:"Meditation",tm:"05:30–05:35",c:"Meditation"},{d:2,t:"Study block",tm:"45 min",c:"Study"},{d:2,t:"Chess practice",tm:"20 min",c:"Chess"},{d:2,t:"School",tm:"08:15–15:30",c:"Study",f:1},{d:2,t:"Travel to work",tm:"15:30–16:00",c:"Commute",f:1},{d:2,t:"Work",tm:"16:00–20:00",c:"Work",f:1},{d:2,t:"Travel home",tm:"20:00–21:00",c:"Commute",f:1},{d:2,t:"Dinner and wind-down",tm:"21:00–21:30",c:"Personal"},
{d:3,t:"Wake up",tm:"05:30",c:"Sleep"},{d:3,t:"Meditation",tm:"5 min",c:"Meditation"},{d:3,t:"Badminton",tm:"Weekly session",c:"Badminton"},{d:3,t:"Legs · core workout",tm:"After badminton · about 60 min",c:"Gym"},{d:3,t:`${skill} practice`,tm:"10–15 min if energy is good",c:"Calisthenics"},
{d:4,t:"Wake up",tm:"05:30",c:"Sleep"},{d:4,t:"Meditation",tm:"05:30–05:35",c:"Meditation"},{d:4,t:"Quick breakfast and prepare",tm:"05:35–05:45",c:"Personal"},{d:4,t:"Travel to fitness center",tm:"05:45–06:25",c:"Commute",f:1},{d:4,t:"Upper · core workout",tm:"06:25–07:25",c:"Gym"},{d:4,t:"Shower and change at gym",tm:"07:25–07:40",c:"Personal",f:1},{d:4,t:"Travel directly to school",tm:"07:40–07:55",c:"Commute",f:1},{d:4,t:"Study block",tm:"90 min",c:"Study"},{d:4,t:"Cybersecurity / programming",tm:"60–90 min",c:"Programming"},
{d:5,t:"Wake up",tm:"05:30",c:"Sleep"},{d:5,t:"Meditation",tm:"5 min",c:"Meditation"},{d:5,t:"Lower · full workout",tm:"Core plan + optional extras",c:"Gym"},{d:5,t:"Boxing",tm:"1 session",c:"Boxing"},{d:5,t:"Study block",tm:"90 min",c:"Study"},{d:5,t:`${skill} practice`,tm:"10–15 min",c:"Calisthenics"},{d:5,t:"Online-income project",tm:"60–120 min",c:"Income"},
{d:6,t:"Wake up",tm:"05:30",c:"Sleep"},{d:6,t:"Meditation",tm:"5 min",c:"Meditation"},{d:6,t:"Ironman base",tm:"Easy swim, bike or run",c:"Endurance"},{d:6,t:"School review",tm:"90 min",c:"Study"},{d:6,t:"Chess practice",tm:"20 min",c:"Chess"},{d:6,t:"Plan next week",tm:"15 min",c:"Planning"}
];
for(let d=0;d<7;d++){a.push({d,t:"Daily stretching",tm:"10 min",c:"Stretching"});a.push({d,t:"In bed by 21:30",tm:"21:30",c:"Sleep"})}
return a.map((x,i)=>({id:`base-${i}`,f:0,...x}))
}
function fresh(){return{week:wk(),done:{},water:{},skill:"Handstand",custom:[],history:{},quests:[
{name:"Live and work in Japan",p:20},{name:"Reach conversational Japanese",p:15},{name:"Build cybersecurity career",p:10},{name:"Complete an Ironman",p:5},{name:"Climb Mount Everest",p:1},{name:"Master calisthenics skill",p:10}
]}}
function load(){let s;try{s=JSON.parse(localStorage.getItem(KEY))}catch{};s=s||fresh();if(s.week!==wk()){s.history[s.week]=s.done;s.week=wk();s.done={};s.custom=[]}return s}let S=load();function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function all(){return[...tasks(S.skill),...S.custom]} function done(x){return!!S.done[x]}
function toggle(x,f){if(f)return;S.done[x]=!S.done[x];save();render()}
function levelInfo(total){let level=1,need=500,left=total;while(left>=need){left-=need;level++;need=400+100*level}return{level,left,need}}
function dailyComplete(d){let A=all();return["Meditation","Stretching"].every(c=>A.some(x=>x.d===d&&x.c===c&&done(x.id)))&&A.filter(x=>x.d===d&&x.c==="Sleep").some(x=>x.t.includes("21:30")&&done(x.id))&&(S.water[dateForDay(d)]||0)>=2500}
function dateForDay(d){let x=monday();x.setDate(x.getDate()+d);return dk(x)}
function streak(){let i=tid()-1,c=0;for(;i>=0;i--){if(dailyComplete(i))c++;else break}return c}
function mult(n){return n>=30?1.2:n>=14?1.15:n>=7?1.1:n>=3?1.05:1}
function totalXP(){let m=mult(streak()),sum=0;all().forEach(x=>{if(done(x.id))sum+=XP[x.c]||0});for(let d=0;d<7;d++)if((S.water[dateForDay(d)]||0)>=2500)sum+=20;return Math.round(sum*m)}
function taskHTML(x){const status=x.f?`<span class="calendar-badge" aria-label="Scheduled event">CAL</span>`:`<button class="check" data-id="${x.id}">${done(x.id)?"✓":""}</button>`;return `<div class="task ${x.f?"scheduled":""} ${done(x.id)?"done":""}"><div class="ico">${ICON[x.c]||"•"}</div><div><div class="title">${x.t}</div><div class="meta">${x.tm}${x.f?" · Scheduled event":""}${!x.f&&XP[x.c]?` · ${XP[x.c]} XP`:""}</div></div>${status}</div>`}
function render(){let A=all(),d=tid(),T=A.filter(x=>x.d===d),act=T.filter(x=>!x.f),n=act.filter(x=>done(x.id)).length,p=act.length?Math.round(n/act.length*100):100;
document.querySelector("#todayName").textContent=DAYS[d];document.querySelector("#summary").textContent=`${act.length-n} personal tasks remaining`;document.querySelector("#pct").textContent=p+"%";document.querySelector("#ring").style.setProperty("--p",p);document.querySelector("#todayCount").textContent=T.length+" tasks";document.querySelector("#todayTasks").innerHTML=T.map(taskHTML).join("");
let xp=totalXP(),li=levelInfo(xp);document.querySelector("#level").textContent=li.level;document.querySelector("#xpText").textContent=`${li.left}/${li.need} XP`;document.querySelector("#streak").textContent=streak()+" days";document.querySelector("#mult").textContent=mult(streak()).toFixed(2)+"× XP";
let w=S.water[dk(new Date())]||0;document.querySelector("#water").textContent=(w/1000).toFixed(1);document.querySelector("#wbar").style.width=Math.min(100,w/25)+"%";
let mo=monday(),su=new Date(mo);su.setDate(mo.getDate()+6);let f=new Intl.DateTimeFormat("en-DK",{day:"numeric",month:"short"});document.querySelector("#weekLabel").textContent=`${f.format(mo)} – ${f.format(su)}`;
document.querySelector("#weekDays").innerHTML=DAYS.map((name,i)=>`<div class="day"><div class="dayHead"><b>${name}</b><span class="muted">${A.filter(x=>x.d===i&&!x.f&&done(x.id)).length}/${A.filter(x=>x.d===i&&!x.f).length}</span></div><div class="dayBody timeline">${A.filter(x=>x.d===i).map(x=>`<div class="event ${x.f?"scheduled-event":""}"><strong>${x.tm} · ${x.t}</strong><div class="muted">${x.f?"Scheduled event":`${x.c}${XP[x.c]?` · ${XP[x.c]} XP`:""}`}</div></div>`).join("")}</div></div>`).join("");
document.querySelector("#questList").innerHTML=S.quests.map(q=>`<div class="card"><div class="quest"><b>${q.name}</b><span>${q.p}%</span></div><div class="bar"><span style="width:${q.p}%"></span></div></div>`).join("");
let ach=[["First 500 XP",xp>=500],["7-day streak",streak()>=7],["Complete both chess sessions",A.filter(x=>x.c==="Chess").every(x=>done(x.id))],["Perfect hydration week",[0,1,2,3,4,5,6].every(i=>(S.water[dateForDay(i)]||0)>=2500)]];
document.querySelector("#achievements").innerHTML=ach.map(a=>`<div class="card" style="opacity:${a[1]?1:.5}"><b>${a[1]?"🏆":"○"} ${a[0]}</b></div>`).join("");document.querySelector("#skill").value=S.skill;
document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>toggle(b.dataset.id,false));
}
document.querySelector("#wplus").onclick=()=>{let k=dk(new Date());S.water[k]=Math.min(2500,(S.water[k]||0)+500);save();render()};document.querySelector("#wminus").onclick=()=>{let k=dk(new Date());S.water[k]=Math.max(0,(S.water[k]||0)-500);save();render()};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===b.dataset.view));window.scrollTo(0,0)});
document.querySelector("#customDay").innerHTML=DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join("");document.querySelector("#saveSkill").onclick=()=>{let v=document.querySelector("#skill").value.trim();if(v)S.skill=v;save();render()};document.querySelector("#saveTask").onclick=()=>{let t=document.querySelector("#customTitle").value.trim();if(!t)return;S.custom.push({id:id(),d:+document.querySelector("#customDay").value,t,tm:document.querySelector("#customTime").value||"Flexible",c:"Personal",f:0});save();render()};
document.querySelector("#addBtn").onclick=()=>document.querySelector('[data-view="settings"]').click();
let ios=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=window.matchMedia("(display-mode: standalone)").matches||navigator.standalone;document.querySelector("#install").classList.toggle("show",ios&&!standalone);
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
render();