const VERSION='3.0.0',KEY='questweek.v3',OLD='questweek.v2',DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const XP={Gym:100,Japanese:75,Study:60,Programming:60,Income:60,Badminton:80,Boxing:80,Endurance:90,Calisthenics:35,Chess:30,Meditation:15,Stretching:15,Sleep:30,Planning:20,Personal:10,Commute:0,Work:0};
const ICON={Gym:'🏋️',Japanese:'🇯🇵',Study:'📚',Work:'💼',Commute:'🚌',Badminton:'🏸',Boxing:'🥊',Endurance:'🏊',Calisthenics:'🤸',Chess:'♟️',Meditation:'🧘',Stretching:'🧎',Sleep:'🌙',Programming:'💻',Income:'💰',Planning:'🗓️',Personal:'•'};
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36),dayIndex=()=>{let n=new Date().getDay();return n===0?6:n-1},dateKey=d=>{d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},tomorrowKey=()=>{let d=new Date();d.setDate(d.getDate()+1);return dateKey(d)},weekKey=()=>{let d=new Date(),n=d.getDay();d.setDate(d.getDate()+(n===0?-6:1-n));return dateKey(d)};
const base=(skill='Handstand')=>[
{id:'mon-wake',d:0,t:'Wake up',start:'05:30',end:'05:35',c:'Sleep'},{id:'mon-med',d:0,t:'Meditation',start:'05:35',end:'05:40',c:'Meditation'},{id:'mon-gymtrip',d:0,t:'Travel to fitness center',start:'05:45',end:'06:25',c:'Commute',fixed:true},{id:'mon-push',d:0,t:'Push · core workout',start:'06:25',end:'07:25',c:'Gym',priority:5},{id:'mon-shower',d:0,t:'Shower and change at gym',start:'07:25',end:'07:40',c:'Personal',fixed:true},{id:'mon-schooltrip',d:0,t:'Travel to school',start:'07:40',end:'07:55',c:'Commute',fixed:true},{id:'mon-school',d:0,t:'School',start:'08:15',end:'15:30',c:'Study',fixed:true},{id:'mon-study',d:0,t:'Study block',start:'15:45',end:'16:30',c:'Study',priority:4},{id:'mon-jp',d:0,t:'Japanese class',start:'17:15',end:'19:05',c:'Japanese',fixed:true},{id:'mon-skill',d:0,t:`${skill} practice`,start:'19:30',end:'19:45',c:'Calisthenics',priority:3},
{id:'tue-wake',d:1,t:'Wake up',start:'05:30',end:'05:35',c:'Sleep'},{id:'tue-med',d:1,t:'Meditation',start:'05:35',end:'05:40',c:'Meditation'},{id:'tue-gymtrip',d:1,t:'Travel to fitness center',start:'05:45',end:'06:25',c:'Commute',fixed:true},{id:'tue-pull',d:1,t:'Pull · core workout',start:'06:25',end:'07:25',c:'Gym',priority:5},{id:'tue-shower',d:1,t:'Shower and change at gym',start:'07:25',end:'07:40',c:'Personal',fixed:true},{id:'tue-schooltrip',d:1,t:'Travel to school',start:'07:40',end:'07:55',c:'Commute',fixed:true},{id:'tue-school',d:1,t:'School',start:'08:15',end:'15:30',c:'Study',fixed:true},{id:'tue-worktrip',d:1,t:'Travel to work',start:'15:30',end:'16:00',c:'Commute',fixed:true},{id:'tue-work',d:1,t:'Work',start:'16:00',end:'20:00',c:'Work',fixed:true},{id:'tue-home',d:1,t:'Travel home',start:'20:00',end:'21:00',c:'Commute',fixed:true},{id:'tue-wind',d:1,t:'Dinner and wind-down',start:'21:00',end:'21:30',c:'Personal'},
{id:'wed-wake',d:2,t:'Wake up',start:'05:30',end:'05:35',c:'Sleep'},{id:'wed-med',d:2,t:'Meditation',start:'05:35',end:'05:40',c:'Meditation'},{id:'wed-study',d:2,t:'Study block',start:'06:00',end:'06:45',c:'Study',priority:4},{id:'wed-chess',d:2,t:'Chess practice',start:'06:50',end:'07:10',c:'Chess',priority:2},{id:'wed-school',d:2,t:'School',start:'08:15',end:'15:30',c:'Study',fixed:true},{id:'wed-work',d:2,t:'Work',start:'16:00',end:'20:00',c:'Work',fixed:true},{id:'wed-home',d:2,t:'Travel home',start:'20:00',end:'21:00',c:'Commute',fixed:true},
{id:'thu-wake',d:3,t:'Wake up',start:'05:30',end:'05:35',c:'Sleep'},{id:'thu-med',d:3,t:'Meditation',start:'05:35',end:'05:40',c:'Meditation'},{id:'thu-bad',d:3,t:'Badminton',start:'16:30',end:'18:00',c:'Badminton',priority:5},{id:'thu-legs',d:3,t:'Legs · core workout',start:'18:15',end:'19:15',c:'Gym',priority:5},{id:'thu-skill',d:3,t:`${skill} practice`,start:'19:20',end:'19:35',c:'Calisthenics',priority:2},
{id:'fri-wake',d:4,t:'Wake up',start:'05:30',end:'05:35',c:'Sleep'},{id:'fri-med',d:4,t:'Meditation',start:'05:35',end:'05:40',c:'Meditation'},{id:'fri-gymtrip',d:4,t:'Travel to fitness center',start:'05:45',end:'06:25',c:'Commute',fixed:true},{id:'fri-upper',d:4,t:'Upper · core workout',start:'06:25',end:'07:25',c:'Gym',priority:5},{id:'fri-shower',d:4,t:'Shower and change at gym',start:'07:25',end:'07:40',c:'Personal',fixed:true},{id:'fri-schooltrip',d:4,t:'Travel to school',start:'07:40',end:'07:55',c:'Commute',fixed:true},{id:'fri-study',d:4,t:'Study block',start:'16:00',end:'17:30',c:'Study',priority:4},{id:'fri-code',d:4,t:'Cybersecurity / programming',start:'18:00',end:'19:30',c:'Programming',priority:5},
{id:'sat-wake',d:5,t:'Wake up',start:'05:30',end:'05:35',c:'Sleep'},{id:'sat-med',d:5,t:'Meditation',start:'05:35',end:'05:40',c:'Meditation'},{id:'sat-lower',d:5,t:'Lower · full workout',start:'09:00',end:'10:15',c:'Gym',priority:5},{id:'sat-box',d:5,t:'Boxing',start:'12:00',end:'13:00',c:'Boxing',priority:4},{id:'sat-study',d:5,t:'Study block',start:'14:00',end:'15:30',c:'Study',priority:4},{id:'sat-skill',d:5,t:`${skill} practice`,start:'15:40',end:'15:55',c:'Calisthenics',priority:2},{id:'sat-income',d:5,t:'Online-income project',start:'16:00',end:'18:00',c:'Income',priority:3},
{id:'sun-wake',d:6,t:'Wake up',start:'05:30',end:'05:35',c:'Sleep'},{id:'sun-med',d:6,t:'Meditation',start:'05:35',end:'05:40',c:'Meditation'},{id:'sun-iron',d:6,t:'Ironman base',start:'09:00',end:'10:30',c:'Endurance',priority:5},{id:'sun-study',d:6,t:'School review',start:'13:00',end:'14:30',c:'Study',priority:4},{id:'sun-chess',d:6,t:'Chess practice',start:'14:40',end:'15:00',c:'Chess',priority:2},{id:'sun-plan',d:6,t:'Plan next week',start:'19:00',end:'19:15',c:'Planning',priority:5}
].concat(Array.from({length:7},(_,d)=>[{id:`stretch-${d}`,d,t:'Daily stretching',start:'21:10',end:'21:20',c:'Stretching',priority:3},{id:`sleep-${d}`,d,t:'In bed by 21:30',start:'21:30',end:'21:35',c:'Sleep',priority:5}]).flat());
function fresh(){return{version:VERSION,week:weekKey(),done:{},water:{},skill:'Handstand',custom:[],overrides:{},school:{},history:[],focusHistory:[],milestones:{},money:{japan:0,bmw:0,emergency:0,income:0,spending:0},quests:[{name:'Japan 2027',m:['Save money','Reach Japanese goal','Secure ski resort job','Prepare visa']},{name:'Everest',m:['Finish Ironman','Winter hiking','Climbing course','Expedition plan']},{name:'Cybersecurity',m:['Networking','Linux','Python','CTFs','First job']},{name:'Ironman',m:['Swim base','Bike base','Run base','First triathlon']}],skills:{Networking:35,Linux:25,Python:55,CTFs:15,Speaking:30,Listening:40,Vocabulary:38,Grammar:28,Handstand:45,Planche:8,'Front Lever':14}}}
function migrate(){let s;try{s=JSON.parse(localStorage.getItem(KEY))}catch{};if(s)return Object.assign(fresh(),s);try{let o=JSON.parse(localStorage.getItem(OLD));if(o){let n=fresh();n.done=o.done||{};n.water=o.water||{};n.skill=o.skill||n.skill;n.custom=o.custom||[];n.money=Object.assign(n.money,o.money||{});return n}}catch{}return fresh()}
let S=migrate();
function rollover(){let w=weekKey();if(S.week!==w){S.history.push({week:S.week,xp:totalXP(false),done:Object.keys(S.done).filter(k=>S.done[k]).length,water:Object.values(S.water).filter(v=>v>=2500).length});S.history=S.history.slice(-26);S.week=w;S.done={};S.water={}}}
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));rollover();save();
const mins=t=>{if(!t||!/^\d\d:\d\d$/.test(t))return null;let[a,b]=t.split(':').map(Number);return a*60+b},fmt=(a,b)=>a&&b?`${a}–${b}`:(a||'Flexible');
function tasks(){let A=base(S.skill).map(x=>Object.assign({},x,S.overrides[x.id]||{}));let tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);let ti=(dayIndex()+1)%7,sc=S.school[dateKey(tomorrow)];if(sc){let school=A.find(x=>x.d===ti&&x.t==='School');if(school){school.start=sc.start;school.end=sc.end}if(ti===1){let trip=A.find(x=>x.id==='tue-worktrip');if(trip)trip.start=sc.end}}return A.concat(S.custom)}
const done=id=>!!S.done[id],toggle=id=>{S.done[id]=!S.done[id];save();render()};
function conflicts(A){let out=new Set;for(let d=0;d<7;d++){let x=A.filter(t=>t.d===d&&mins(t.start)!=null&&mins(t.end)!=null).sort((a,b)=>mins(a.start)-mins(b.start));for(let i=1;i<x.length;i++)if(mins(x[i].start)<mins(x[i-1].end)){out.add(x[i].id);out.add(x[i-1].id)}}return out}
function warningList(A){let c=conflicts(A),w=[];if(c.size)w.push(`${c.size} events overlap.`);for(let d=0;d<7;d++){let late=A.some(x=>x.d===d&&mins(x.end)>1290&&!x.t.includes('21:30'));if(late)w.push(`${DAYS[d]} has an event after your 21:30 bedtime.`)}return w}
function level(total){let l=1,n=500,r=total;while(r>=n){r-=n;l++;n=400+100*l}return{l,n,r}}
function streak(){let A=tasks(),d=dayIndex()-1,s=0;for(;d>=0;d--){let ok=['Meditation','Stretching'].every(c=>A.some(x=>x.d===d&&x.c===c&&done(x.id)))&&A.some(x=>x.d===d&&x.t.includes('21:30')&&done(x.id))&&(S.water[d]||0)>=2500;if(!ok)break;s++}return s}
const mult=s=>s>=30?1.2:s>=14?1.15:s>=7?1.1:s>=3?1.05:1;
function totalXP(includeMilestones=true){let sum=tasks().reduce((a,x)=>a+(done(x.id)?Number(x.xp??XP[x.c]??0):0),0)+Object.values(S.water).filter(v=>v>=2500).length*20;if(includeMilestones)sum+=Object.values(S.milestones).filter(Boolean).length*100;return Math.round(sum*mult(streak()))}
function mainQuest(P){return P.filter(x=>!done(x.id)).sort((a,b)=>(b.priority||1)-(a.priority||1)||mins(a.start)-mins(b.start))[0]||{t:'Day complete',start:'',end:'',c:'Planning',id:''}}
function taskHTML(x,C){return `<div class="task ${x.fixed?'scheduled':''} ${done(x.id)?'done':''}" data-edit="${x.id}"><div class="ico">${ICON[x.c]||'•'}</div><div><div class="title">${x.t}</div><div class="meta">${fmt(x.start,x.end)}${x.fixed?' · Scheduled event':` · ${x.xp??XP[x.c]??0} XP`}${C.has(x.id)?' · CONFLICT':''}</div></div>${x.fixed?'<span class="calendarBadge">CAL</span>':`<button class="check" data-check="${x.id}">${done(x.id)?'✓':''}</button>`}</div>`}
function screen(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0)}
let timer=null,remaining=0,focusTask=null;
function startFocus(x){focusTask=x;remaining=Math.max(60,(mins(x.end)-mins(x.start))*60||3600);document.querySelector('#focusTitle').textContent=x.t;document.querySelector('#focusOverlay').classList.add('show');paintTimer();clearInterval(timer);timer=setInterval(()=>{remaining--;paintTimer();if(remaining<=0)finishFocus(true)},1000)}
function paintTimer(){let m=Math.floor(remaining/60),s=remaining%60;document.querySelector('#focusTime').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function finishFocus(complete=false){clearInterval(timer);if(focusTask)S.focusHistory.push({task:focusTask.t,date:new Date().toISOString(),seconds:Math.max(0,(mins(focusTask.end)-mins(focusTask.start))*60-remaining),complete});if(complete&&focusTask&&!focusTask.fixed)S.done[focusTask.id]=true;save();document.querySelector('#focusOverlay').classList.remove('show');render()}
function openEdit(id){let x=tasks().find(t=>t.id===id);if(!x)return;document.querySelector('#editId').value=x.id;document.querySelector('#editTitle').value=x.t;document.querySelector('#editDay').value=x.d;document.querySelector('#editStart').value=x.start||'';document.querySelector('#editEnd').value=x.end||'';document.querySelector('#editXP').value=x.xp??XP[x.c]??0;document.querySelector('#editFixed').checked=!!x.fixed;document.querySelector('#editModal').classList.add('show')}
function render(){let A=tasks(),d=dayIndex(),T=A.filter(x=>x.d===d),P=T.filter(x=>!x.fixed),C=conflicts(A),completed=P.filter(x=>done(x.id)).length,p=P.length?Math.round(completed/P.length*100):100,xp=totalXP(),L=level(xp),main=mainQuest(P),warn=warningList(A);
document.querySelector('#todayName').textContent=DAYS[d];document.querySelector('#todayPct').textContent=p+'%';document.querySelector('#todayRing').style.setProperty('--p',p);document.querySelector('#levelNo').textContent='Level '+L.l;document.querySelector('#levelXP').textContent=`${L.r}/${L.n} XP`;document.querySelector('#streakNo').textContent=streak()+' days';document.querySelector('#multi').textContent=mult(streak()).toFixed(2)+'× multiplier';document.querySelector('#warnings').innerHTML=warn.length?warn.map(x=>`<div class="warning">⚠️ ${x}</div>`).join(''):'<div class="success">✓ No schedule conflicts detected.</div>';document.querySelector('#mainQuest').innerHTML=`<div class="pill">SMART MAIN QUEST</div><h2 style="margin-top:10px">${ICON[main.c]||'🎯'} ${main.t}</h2><p class="muted" style="margin-top:6px">${fmt(main.start,main.end)}</p>${main.id?'<button class="btn" id="focusBtn" style="margin-top:14px">Start Focus Mode</button>':''}`;document.querySelector('#todayTasks').innerHTML=T.map(x=>taskHTML(x,C)).join('');let w=S.water[d]||0;document.querySelector('#waterText').textContent=(w/1000).toFixed(1)+' / 2.5 L';document.querySelector('#waterBar').style.width=Math.min(100,w/25)+'%';
document.querySelector('#timeline').innerHTML=DAYS.map((day,i)=>`<div class="sectionHead"><h2>${day}</h2><span class="pill">${A.filter(x=>x.d===i&&!x.fixed&&done(x.id)).length}/${A.filter(x=>x.d===i&&!x.fixed).length}</span></div><div class="timeline">${A.filter(x=>x.d===i).sort((a,b)=>(mins(a.start)||9999)-(mins(b.start)||9999)).map(x=>`<div class="event ${x.fixed?'scheduledEvent':''} ${C.has(x.id)?'conflict':''}" data-edit="${x.id}"><b>${fmt(x.start,x.end)}</b><div>${ICON[x.c]||'•'} ${x.t}</div><div class="muted">${x.fixed?'Scheduled event':`${x.c} · ${x.xp??XP[x.c]??0} XP`}</div></div>`).join('')}</div>`).join('');
document.querySelector('#questList').innerHTML=S.quests.map((q,qi)=>{let n=q.m.filter((_,mi)=>S.milestones[`${qi}-${mi}`]).length,pct=Math.round(n/q.m.length*100);return `<div class="card"><div style="display:flex;justify-content:space-between"><h3>${q.name}</h3><b>${pct}%</b></div><div class="bar"><span style="width:${pct}%"></span></div>${q.m.map((m,mi)=>`<label class="task" style="grid-template-columns:1fr auto;margin-top:9px"><span>${m} <span class="muted">· 100 XP</span></span><input type="checkbox" data-mile="${qi}-${mi}" ${S.milestones[`${qi}-${mi}`]?'checked':''}></label>`).join('')}</div>`}).join('');
let hist=S.history.slice(-8),trained=A.filter(x=>['Gym','Badminton','Boxing','Endurance'].includes(x.c)&&done(x.id)).length,studied=A.filter(x=>x.c==='Study'&&done(x.id)).length;document.querySelector('#stats').innerHTML=`<div class="grid"><div class="stat"><span class="muted">Training</span><strong>${trained}</strong><span class="muted">sessions</span></div><div class="stat"><span class="muted">Study</span><strong>${studied}</strong><span class="muted">blocks</span></div><div class="stat"><span class="muted">Weekly XP</span><strong>${xp}</strong></div><div class="stat"><span class="muted">Focus sessions</span><strong>${S.focusHistory.length}</strong></div></div><div class="card"><h3>Saved weekly history</h3>${hist.length?hist.map(h=>`<p class="muted" style="margin-top:9px">${h.week}: ${h.xp} XP · ${h.done} tasks · ${h.water}/7 water days</p>`).join(''):'<p class="muted" style="margin-top:9px">History appears after your first weekly rollover.</p>'}</div>`;
document.querySelector('#skills').innerHTML=Object.entries(S.skills).map(([k,v])=>`<div class="skillRow"><div style="display:flex;justify-content:space-between"><b>${k}</b><span>${v}%</span></div><div class="bar"><span style="width:${v}%"></span></div></div>`).join('');for(let k of ['japan','bmw','emergency','income','spending'])document.querySelector('#m-'+k).value=S.money[k]||0;document.querySelector('#skill').value=S.skill;document.querySelector('#appVersion').textContent='QuestWeek '+VERSION;
let tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);let sc=S.school[dateKey(tomorrow)];document.querySelector('#tomorrowSchoolTitle').textContent=`${DAYS[(d+1)%7]}'s school`;document.querySelector('#schoolStart').value=sc?.start||'08:15';document.querySelector('#schoolEnd').value=sc?.end||'15:30';document.querySelectorAll('[data-check]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggle(b.dataset.check)});document.querySelectorAll('[data-edit]').forEach(e=>e.onclick=ev=>{if(!ev.target.closest('[data-check]'))openEdit(e.dataset.edit)});document.querySelectorAll('[data-mile]').forEach(e=>e.onchange=()=>{S.milestones[e.dataset.mile]=e.checked;save();render()});if(main.id)document.querySelector('#focusBtn').onclick=()=>startFocus(main)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>screen(b.dataset.view));document.querySelector('#waterPlus').onclick=()=>{let d=dayIndex();S.water[d]=Math.min(2500,(S.water[d]||0)+500);save();render()};document.querySelector('#waterMinus').onclick=()=>{let d=dayIndex();S.water[d]=Math.max(0,(S.water[d]||0)-500);save();render()};document.querySelector('#pauseFocus').onclick=()=>{if(timer){clearInterval(timer);timer=null;document.querySelector('#pauseFocus').textContent='Resume'}else{timer=setInterval(()=>{remaining--;paintTimer();if(remaining<=0)finishFocus(true)},1000);document.querySelector('#pauseFocus').textContent='Pause'}};document.querySelector('#completeFocus').onclick=()=>finishFocus(true);document.querySelector('#closeFocus').onclick=()=>finishFocus(false);
document.querySelector('#saveEdit').onclick=()=>{let id=document.querySelector('#editId').value,orig=base(S.skill).find(x=>x.id===id);let data={t:document.querySelector('#editTitle').value.trim(),d:+document.querySelector('#editDay').value,start:document.querySelector('#editStart').value,end:document.querySelector('#editEnd').value,xp:+document.querySelector('#editXP').value,fixed:document.querySelector('#editFixed').checked};if(orig)S.overrides[id]=data;else{let x=S.custom.find(x=>x.id===id);if(x)Object.assign(x,data)}save();document.querySelector('#editModal').classList.remove('show');render()};document.querySelector('#deleteTask').onclick=()=>{let id=document.querySelector('#editId').value;if(S.custom.some(x=>x.id===id))S.custom=S.custom.filter(x=>x.id!==id);else S.overrides[id]={hidden:true};save();document.querySelector('#editModal').classList.remove('show');render()};document.querySelector('#cancelEdit').onclick=()=>document.querySelector('#editModal').classList.remove('show');
document.querySelector('#saveSchoolHours').onclick=()=>{let start=document.querySelector('#schoolStart').value,end=document.querySelector('#schoolEnd').value;if(!start||!end||mins(end)<=mins(start)){document.querySelector('#schoolHoursStatus').textContent='End time must be later than start time.';return}S.school[tomorrowKey()]={start,end};save();document.querySelector('#schoolHoursStatus').textContent=`Saved: ${start}–${end}`;render()};document.querySelector('#saveSkill').onclick=()=>{S.skill=document.querySelector('#skill').value.trim()||'Handstand';save();render()};document.querySelector('#saveMoney').onclick=()=>{for(let k of ['japan','bmw','emergency','income','spending'])S.money[k]=Number(document.querySelector('#m-'+k).value||0);save();render()};document.querySelector('#addTask').onclick=()=>{let t=document.querySelector('#customTitle').value.trim();if(!t)return;S.custom.push({id:'c-'+uid(),d:+document.querySelector('#customDay').value,t,start:document.querySelector('#customStart').value,end:document.querySelector('#customEnd').value,c:document.querySelector('#customCategory').value,xp:+document.querySelector('#customXP').value||20,priority:+document.querySelector('#customPriority').value||1,fixed:false});save();render()};
document.querySelector('#exportData').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='questweek-backup.json';a.click();URL.revokeObjectURL(a.href)};document.querySelector('#importData').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());S=Object.assign(fresh(),x);save();render()}catch{alert('Could not import that backup.')}};document.querySelector('#refreshApp').onclick=async()=>{if('serviceWorker'in navigator){let regs=await navigator.serviceWorker.getRegistrations();for(let r of regs)await r.update()}location.reload(true)};
document.querySelector('#customDay').innerHTML=document.querySelector('#editDay').innerHTML=DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join('');let ios=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone;document.querySelector('#install').classList.toggle('show',ios&&!standalone);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));render();