const QK='questweek.v2',DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const XP={Gym:100,Japanese:75,Study:60,Programming:60,Income:60,Badminton:80,Boxing:80,Endurance:90,Calisthenics:35,Chess:30,Meditation:15,Stretching:15,Sleep:30,Planning:20,Personal:10,Commute:0,Work:0};
const ICON={Gym:'🏋️',Japanese:'🇯🇵',Study:'📚',Work:'💼',Commute:'🚌',Badminton:'🏸',Boxing:'🥊',Endurance:'🏊',Calisthenics:'🤸',Chess:'♟️',Meditation:'🧘',Stretching:'🧎',Sleep:'🌙',Programming:'💻',Income:'💰',Planning:'🗓️',Personal:'•'};
const baseTasks=(skill='Handstand')=>[
{d:0,t:'Wake up',tm:'05:30',c:'Sleep'},{d:0,t:'Meditation',tm:'05:30–05:35',c:'Meditation'},{d:0,t:'Travel to fitness center',tm:'05:45–06:25',c:'Commute',f:1},{d:0,t:'Push · core workout',tm:'06:25–07:25',c:'Gym'},{d:0,t:'Shower and change at gym',tm:'07:25–07:40',c:'Personal',f:1},{d:0,t:'Travel to school',tm:'07:40–07:55',c:'Commute',f:1},{d:0,t:'School',tm:'08:15 onward',c:'Study',f:1},{d:0,t:'Study block',tm:'30–45 min before Japanese',c:'Study'},{d:0,t:'Japanese class',tm:'17:15–19:05',c:'Japanese',f:1},{d:0,t:`${skill} practice`,tm:'10–15 min after class',c:'Calisthenics'},
{d:1,t:'Wake up',tm:'05:30',c:'Sleep'},{d:1,t:'Meditation',tm:'05:30–05:35',c:'Meditation'},{d:1,t:'Travel to fitness center',tm:'05:45–06:25',c:'Commute',f:1},{d:1,t:'Pull · core workout',tm:'06:25–07:25',c:'Gym'},{d:1,t:'Shower and change at gym',tm:'07:25–07:40',c:'Personal',f:1},{d:1,t:'Travel to school',tm:'07:40–07:55',c:'Commute',f:1},{d:1,t:'School',tm:'08:15–15:30',c:'Study',f:1},{d:1,t:'Travel to work',tm:'15:30–16:00',c:'Commute',f:1},{d:1,t:'Work',tm:'16:00–20:00',c:'Work',f:1},{d:1,t:'Travel home',tm:'20:00–21:00',c:'Commute',f:1},{d:1,t:'Dinner and wind-down',tm:'21:00–21:30',c:'Personal'},
{d:2,t:'Wake up',tm:'05:30',c:'Sleep'},{d:2,t:'Meditation',tm:'05:30–05:35',c:'Meditation'},{d:2,t:'Study block',tm:'45 min',c:'Study'},{d:2,t:'Chess practice',tm:'20 min',c:'Chess'},{d:2,t:'School',tm:'08:15–15:30',c:'Study',f:1},{d:2,t:'Work',tm:'16:00–20:00',c:'Work',f:1},{d:2,t:'Travel home',tm:'20:00–21:00',c:'Commute',f:1},
{d:3,t:'Wake up',tm:'05:30',c:'Sleep'},{d:3,t:'Meditation',tm:'5 min',c:'Meditation'},{d:3,t:'Badminton',tm:'Weekly session',c:'Badminton'},{d:3,t:'Legs · core workout',tm:'After badminton · about 60 min',c:'Gym'},{d:3,t:`${skill} practice`,tm:'10–15 min if energy is good',c:'Calisthenics'},
{d:4,t:'Wake up',tm:'05:30',c:'Sleep'},{d:4,t:'Meditation',tm:'05:30–05:35',c:'Meditation'},{d:4,t:'Travel to fitness center',tm:'05:45–06:25',c:'Commute',f:1},{d:4,t:'Upper · core workout',tm:'06:25–07:25',c:'Gym'},{d:4,t:'Shower and change at gym',tm:'07:25–07:40',c:'Personal',f:1},{d:4,t:'Travel to school',tm:'07:40–07:55',c:'Commute',f:1},{d:4,t:'Study block',tm:'90 min',c:'Study'},{d:4,t:'Cybersecurity / programming',tm:'60–90 min',c:'Programming'},
{d:5,t:'Wake up',tm:'05:30',c:'Sleep'},{d:5,t:'Meditation',tm:'5 min',c:'Meditation'},{d:5,t:'Lower · full workout',tm:'Core plan + optional extras',c:'Gym'},{d:5,t:'Boxing',tm:'1 session',c:'Boxing'},{d:5,t:'Study block',tm:'90 min',c:'Study'},{d:5,t:`${skill} practice`,tm:'10–15 min',c:'Calisthenics'},{d:5,t:'Online-income project',tm:'60–120 min',c:'Income'},
{d:6,t:'Wake up',tm:'05:30',c:'Sleep'},{d:6,t:'Meditation',tm:'5 min',c:'Meditation'},{d:6,t:'Ironman base',tm:'Easy swim, bike or run',c:'Endurance'},{d:6,t:'School review',tm:'90 min',c:'Study'},{d:6,t:'Chess practice',tm:'20 min',c:'Chess'},{d:6,t:'Plan next week',tm:'15 min',c:'Planning'}
].concat(Array.from({length:7},(_,d)=>[{d,t:'Daily stretching',tm:'10 min',c:'Stretching'},{d,t:'In bed by 21:30',tm:'21:30',c:'Sleep'}]).flat()).map((x,i)=>({id:`q-${i}`,f:0,...x}));
function fresh(){return{done:{},water:{},skill:'Handstand',custom:[],money:{japan:0,bmw:0,emergency:0,income:0,spending:0},quests:[{name:'Japan 2027',p:20,m:['Save money','Reach Japanese goal','Secure ski resort job','Prepare visa']},{name:'Everest',p:5,m:['Finish Ironman','Winter hiking','Climbing course','Expedition plan']},{name:'Cybersecurity',p:12,m:['Networking','Linux','Python','CTFs','First job']},{name:'Ironman',p:8,m:['Swim base','Bike base','Run base','First triathlon']}],skills:{Networking:35,Linux:25,Python:55,CTFs:15,Speaking:30,Listening:40,Vocabulary:38,Grammar:28,Handstand:45,Planche:8,'Front Lever':14}}}
let S;try{S=JSON.parse(localStorage.getItem(QK))||fresh()}catch{S=fresh()}const save=()=>localStorage.setItem(QK,JSON.stringify(S));
const nowDay=()=>{let n=new Date().getDay();return n===0?6:n-1},all=()=>[...baseTasks(S.skill),...S.custom],done=id=>!!S.done[id];
function toggle(id){S.done[id]=!S.done[id];save();render()}
function level(total){let l=1,n=500,r=total;while(r>=n){r-=n;l++;n=400+100*l}return{l,n,r}}
function streak(){let A=all(),d=nowDay()-1,s=0;for(;d>=0;d--){let ok=['Meditation','Stretching'].every(c=>A.some(x=>x.d===d&&x.c===c&&done(x.id)))&&A.some(x=>x.d===d&&x.t.includes('21:30')&&done(x.id))&&(S.water[d]||0)>=2500;if(!ok)break;s++}return s}
const mult=s=>s>=30?1.2:s>=14?1.15:s>=7?1.1:s>=3?1.05:1;
function totalXP(){let sum=all().reduce((a,x)=>a+(done(x.id)?XP[x.c]||0:0),0)+Object.values(S.water).filter(v=>v>=2500).length*20;return Math.round(sum*mult(streak()))}
function taskHTML(x){const action=x.f?`<span class="calendarBadge">CAL</span>`:`<button class="check" data-check="${x.id}">${done(x.id)?'✓':''}</button>`;return `<div class="task ${x.f?'scheduled':''} ${done(x.id)?'done':''}"><div class="ico">${ICON[x.c]||'•'}</div><div><div class="title">${x.t}</div><div class="meta">${x.tm}${x.f?' · Scheduled event':XP[x.c]?` · ${XP[x.c]} XP`:''}</div></div>${action}</div>`}
function screen(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===name));scrollTo(0,0)}
function render(){let A=all(),d=nowDay(),T=A.filter(x=>x.d===d),P=T.filter(x=>!x.f),c=P.filter(x=>done(x.id)).length,p=P.length?Math.round(c/P.length*100):100,xp=totalXP(),L=level(xp),main=P.find(x=>!done(x.id))||{t:'Day complete',tm:'Everything planned is done',c:'Planning'};
document.querySelector('#todayName').textContent=DAYS[d];document.querySelector('#todayPct').textContent=p+'%';document.querySelector('#todayRing').style.setProperty('--p',p);document.querySelector('#levelNo').textContent='Level '+L.l;document.querySelector('#levelXP').textContent=`${L.r}/${L.n} XP`;document.querySelector('#streakNo').textContent=streak()+' days';document.querySelector('#multi').textContent=mult(streak()).toFixed(2)+'× multiplier';document.querySelector('#mainQuest').innerHTML=`<div class="pill">MAIN QUEST</div><h2 style="margin-top:10px">${ICON[main.c]||'🎯'} ${main.t}</h2><p class="muted" style="margin-top:6px">${main.tm}</p><button class="btn" id="focusBtn" style="margin-top:14px">Start Focus Mode</button>`;document.querySelector('#todayTasks').innerHTML=T.map(taskHTML).join('');
let w=S.water[d]||0;document.querySelector('#waterText').textContent=(w/1000).toFixed(1)+' / 2.5 L';document.querySelector('#waterBar').style.width=Math.min(100,w/25)+'%';
document.querySelector('#timeline').innerHTML=DAYS.map((day,i)=>`<div class="sectionHead"><h2>${day}</h2><span class="pill">${A.filter(x=>x.d===i&&!x.f&&done(x.id)).length}/${A.filter(x=>x.d===i&&!x.f).length}</span></div><div class="timeline">${A.filter(x=>x.d===i).map(x=>`<div class="event ${x.f?'scheduledEvent':''}"><b>${x.tm}</b><div>${ICON[x.c]||'•'} ${x.t}</div><div class="muted">${x.f?'Scheduled event':x.c}</div></div>`).join('')}</div>`).join('');
document.querySelector('#questList').innerHTML=S.quests.map((q,qi)=>`<div class="card"><div style="display:flex;justify-content:space-between"><h3>${q.name}</h3><b>${q.p}%</b></div><div class="bar"><span style="width:${q.p}%"></span></div>${q.m.map((m,mi)=>`<label class="task" style="grid-template-columns:1fr auto;margin-top:9px"><span>${m}</span><input type="checkbox" data-mile="${qi}-${mi}"></label>`).join('')}</div>`).join('');
let trained=A.filter(x=>['Gym','Badminton','Boxing','Endurance'].includes(x.c)&&done(x.id)).length,studied=A.filter(x=>x.c==='Study'&&done(x.id)).length,prog=A.filter(x=>x.c==='Programming'&&done(x.id)).length;document.querySelector('#stats').innerHTML=`<div class="grid"><div class="stat"><span class="muted">Training</span><strong>${trained}</strong><span class="muted">sessions</span></div><div class="stat"><span class="muted">Study</span><strong>${studied}</strong><span class="muted">blocks</span></div><div class="stat"><span class="muted">Programming</span><strong>${prog}</strong><span class="muted">blocks</span></div><div class="stat"><span class="muted">Weekly XP</span><strong>${xp}</strong><span class="muted">earned</span></div></div><div class="card"><h3>Habit heatmap</h3><div class="heat" style="margin-top:12px">${Array.from({length:28},(_,i)=>`<div class="${i<Math.min(28,Object.keys(S.done).length)?'on':''}"></div>`).join('')}</div></div>`;
document.querySelector('#skills').innerHTML=Object.entries(S.skills).map(([k,v])=>`<div class="skillRow"><div style="display:flex;justify-content:space-between"><b>${k}</b><span>${v}%</span></div><div class="bar"><span style="width:${v}%"></span></div></div>`).join('');
document.querySelector('#dreams').innerHTML=[['🇯🇵','Live in Japan'],['🏔️','Climb Everest'],['🏊','Finish Ironman'],['🚗','Buy BMW M4'],['💻','Cybersecurity career'],['🎿','Work at ski resort']].map(x=>`<div class="dream">${x[0]}<b>${x[1]}</b></div>`).join('');
for(let k of ['japan','bmw','emergency','income','spending'])document.querySelector('#m-'+k).value=S.money[k]||0;document.querySelector('#skill').value=S.skill;document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>toggle(b.dataset.check));document.querySelector('#focusBtn').onclick=()=>{document.querySelector('#focusTitle').textContent=main.t;document.querySelector('#focusTime').textContent='60:00';document.querySelector('#focusOverlay').classList.add('show')};}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>screen(b.dataset.view));document.querySelector('#waterPlus').onclick=()=>{let d=nowDay();S.water[d]=Math.min(2500,(S.water[d]||0)+500);save();render()};document.querySelector('#waterMinus').onclick=()=>{let d=nowDay();S.water[d]=Math.max(0,(S.water[d]||0)-500);save();render()};document.querySelector('#closeFocus').onclick=()=>document.querySelector('#focusOverlay').classList.remove('show');document.querySelector('#saveSkill').onclick=()=>{S.skill=document.querySelector('#skill').value.trim()||'Handstand';save();render()};document.querySelector('#saveMoney').onclick=()=>{for(let k of ['japan','bmw','emergency','income','spending'])S.money[k]=Number(document.querySelector('#m-'+k).value||0);save();render()};document.querySelector('#addTask').onclick=()=>{let t=document.querySelector('#customTitle').value.trim();if(!t)return;S.custom.push({id:'c-'+Date.now(),d:+document.querySelector('#customDay').value,t,tm:document.querySelector('#customTime').value||'Flexible',c:'Personal',f:0});save();render()};document.querySelector('#customDay').innerHTML=DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join('');let ios=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone;document.querySelector('#install').classList.toggle('show',ios&&!standalone);render();