(()=>{'use strict';
const RECIPES=[
{name:'Chicken Curry & Rice',cost:27,protein:'High protein',items:['1 kg chicken breast','500 g rice','2 cans chopped tomatoes','400 ml light coconut milk','2 onions','Frozen mixed vegetables','Curry powder','Garlic']},
{name:'Chili Con Carne & Rice',cost:25,protein:'High protein',items:['750 g lean minced beef','500 g rice','2 cans kidney beans','2 cans chopped tomatoes','2 onions','Frozen peppers','Chili seasoning','Garlic']},
{name:'Teriyaki Chicken & Rice',cost:30,protein:'High protein',items:['1 kg chicken breast','500 g rice','750 g frozen broccoli','Soy sauce','Honey','Garlic','Ginger','Cornstarch']},
{name:'Chicken Pasta Bolognese',cost:28,protein:'High protein',items:['900 g chicken mince','600 g pasta','2 cans chopped tomatoes','2 onions','500 g frozen vegetables','Tomato purée','Italian herbs','Garlic']},
{name:'Mexican Chicken Bowls',cost:31,protein:'High protein',items:['1 kg chicken breast','500 g rice','1 can black beans','1 can corn','Frozen peppers','Salsa','Mexican seasoning','Lime']},
{name:'Chicken Fried Rice',cost:24,protein:'High protein',items:['900 g chicken breast','500 g rice','6 eggs','750 g frozen mixed vegetables','Soy sauce','Garlic','Spring onion']},
{name:'Greek Chicken & Potatoes',cost:32,protein:'High protein',items:['1 kg chicken breast','1.5 kg potatoes','500 g frozen green beans','Greek yogurt','Lemon','Garlic','Oregano']},
{name:'BBQ Chicken Pasta',cost:30,protein:'High protein',items:['1 kg chicken breast','600 g pasta','500 g frozen vegetables','BBQ sauce','Greek yogurt','Paprika','Garlic']}
];
S.mealPrep=Object.assign({enabled:true,total:5,left:5,recipe:0,shopping:{},lastPrep:'',weekKey:''},S.mealPrep||{});
const weekKey=()=>{const d=new Date(),x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return x.getUTCFullYear()+'-W'+String(Math.ceil((((x-y)/86400000)+1)/7)).padStart(2,'0')};
function rotateWeek(){const k=weekKey();if(S.mealPrep.weekKey!==k){S.mealPrep.weekKey=k;S.mealPrep.recipe=(S.mealPrep.recipe+1)%RECIPES.length;S.mealPrep.shopping={};save()}}
function nextSunday(){const d=new Date(),add=(7-d.getDay())%7||7,n=new Date(d);n.setDate(d.getDate()+add);return n.toLocaleDateString('en-DK',{weekday:'long',day:'numeric',month:'short'})}
function recipe(){return RECIPES[S.mealPrep.recipe%RECIPES.length]}
function openMealSheet(){const r=recipe();sheet.innerHTML=`<button class="close-x" data-close>×</button><span class="pill">SCHOOL LUNCH PREP</span><h2 style="margin-top:10px">${e(r.name)}</h2><p class="muted" style="margin-top:6px">Makes 5 school lunches · estimated ${r.cost} kr per meal · ${r.protein}</p><div class="bar" style="margin-top:14px"><span style="width:${S.mealPrep.left/5*100}%"></span></div><p style="margin-top:8px"><b>${S.mealPrep.left} of 5 lunches remaining</b></p><div class="head"><h3>Shopping list</h3></div>${r.items.map((item,i)=>`<label style="display:flex;gap:10px;align-items:center;margin-top:10px"><input type="checkbox" data-meal-shop="${i}" ${S.mealPrep.shopping[i]?'checked':''}> <span>${e(item)}</span></label>`).join('')}<div class="row wrap" style="margin-top:18px"><button class="btn" data-meal-action="prepped">Prepared 5 lunches</button><button class="btn secondary" data-meal-action="next">Change recipe</button></div>`;modal.classList.add('show')}
function mealCard(){const r=recipe(),due=S.mealPrep.left===0;return `<div id="mealPrepCard" class="card" style="margin-top:10px"><div class="section-title"><div><span class="pill">🍱 SCHOOL LUNCH PREP</span><h2 style="margin-top:8px">${e(r.name)}</h2></div><strong>${S.mealPrep.left}/5</strong></div><p class="muted" style="margin-top:6px">${r.cost} kr per meal · Next prep: ${nextSunday()}</p><div class="bar" style="margin-top:12px"><span style="width:${S.mealPrep.left/5*100}%"></span></div>${due?'<div class="warning" style="margin-top:10px">All school lunches are used. Prep five more this Sunday.</div>':''}<div class="row wrap" style="margin-top:12px"><button class="btn" data-meal-action="eat" ${S.mealPrep.left<=0?'disabled':''}>Mark lunch eaten</button><button class="btn secondary" data-meal-action="open">Shopping list</button></div></div>`}
function enhanceMealPrep(){rotateWeek();const root=document.getElementById('home');if(!root)return;document.getElementById('mealPrepCard')?.remove();const water=[...root.querySelectorAll('.card')].find(c=>c.textContent.includes('WATER'));if(water)water.insertAdjacentHTML('afterend',mealCard());else root.insertAdjacentHTML('beforeend',mealCard());
const planner=document.getElementById('planner');if(planner&&!planner.querySelector('#mealPrepPlanner')){const sundayHeads=[...planner.querySelectorAll('.head')].filter(h=>h.textContent.trim().startsWith('Sunday'));const target=sundayHeads[0]?.nextElementSibling;if(target){target.insertAdjacentHTML('beforeend','<div id="mealPrepPlanner" class="event"><b>Flexible · 1h 45m</b><div>🍱 School Lunch Prep</div><div class="muted">Prepare 5 Monday–Friday lunches</div></div>')}}
const smart=[...root.querySelectorAll('.card')].find(c=>c.textContent.includes('SMART PLANNER'));if(smart&&S.mealPrep.left===0){const h=smart.querySelector('h2'),p=smart.querySelector('p');if(h)h.textContent='School lunch prep is due';if(p)p.textContent='Prepare five lunches on Sunday. Smart Planner will keep this inside your awake hours.'}}
const baseRender=render;render=function(){baseRender();requestAnimationFrame(enhanceMealPrep)};
document.addEventListener('change',ev=>{if(ev.target.matches('[data-meal-shop]')){S.mealPrep.shopping[ev.target.dataset.mealShop]=ev.target.checked;save()}});
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-meal-action]');if(!b)return;ev.preventDefault();const a=b.dataset.mealAction;if(a==='open')openMealSheet();if(a==='eat'&&S.mealPrep.left>0){S.mealPrep.left--;save();render();if(typeof toast==='function')toast('School lunch marked as eaten')}if(a==='prepped'){S.mealPrep.left=5;S.mealPrep.shopping={};S.mealPrep.lastPrep=new Date().toISOString().slice(0,10);save();modal.classList.remove('show');render();if(typeof toast==='function')toast('Five school lunches are ready')}if(a==='next'){S.mealPrep.recipe=(S.mealPrep.recipe+1)%RECIPES.length;S.mealPrep.shopping={};save();openMealSheet();render()}});
render();
})();