(()=>{'use strict';
const HELP={xp:['XP & Levels','XP rewards activities that move your goals forward. Meals, school, work, travel and sleep give 0 XP so routine commitments do not inflate your level.'],health:['Health Score','Health reflects completed meals, hydration and your recovery check-in. It is separate from XP because health is maintenance, not a game reward.'],burnout:['Burnout Risk','Burnout uses your stress, fatigue, recovery and recent intense training. A high result makes Smart Planner prefer recovery instead of adding work.'],stats:['Weekly Statistics','Time is counted from tasks you mark complete. Fixed events remain visible in your schedule, but only completed activities contribute to your progress totals.'],streaks:['Streaks','A streak shows how consistently you complete a category. Completing at least one matching task on a day maintains that streak.'],smart:['Smart Planner','Smart Planner checks your remaining schedule, sleep boundary, recent focus balance and burnout risk. It suggests only work that fits into a realistic free gap.'],life:['Life Stats','Strength rises from training; Knowledge from study, Japanese and programming; Discipline from consistency; Endurance from cardio; Wealth from side hustle; Adventure from milestones; Balance from recovery habits.'],holiday:['Holiday Modes','Normal uses school and work. Holiday at Home keeps work and a maximum of two focus blocks daily. Holiday Away prioritizes exploring, movement and recovery. Intensity changes session length and protected free time.'],goals:['Goal Progress','Each goal percentage is based on completed milestone checkboxes. Countdowns measure time only; milestones measure actual preparation.'],challenges:['Challenges','Use the + button to add verified progress. Challenges are cumulative and do not reset weekly.'],photos:['Progress Photos','Upload consistent front, side or back photos. Tap two photos to compare them side by side. Photos stay in this browser, so export backups regularly.']};
S.ui=Object.assign({tourDone:false,favorites:[],pinnedGoals:[],lastVersion:'',undo:null,photoCompare:[]},S.ui||{});save();
const toast=text=>{const x=document.getElementById('toast');if(!x)return;x.textContent=text;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2200);if(navigator.vibrate)navigator.vibrate(15)};
const help=key=>{const h=HELP[key]||['QuestWeek','This feature helps you understand and improve your week.'];sheet.innerHTML=`<button class="close-x" data-close>×</button><span class="pill">HOW IT WORKS</span><h2 style="margin-top:12px">${e(h[0])}</h2><p class="muted" style="margin-top:10px;line-height:1.55">${e(h[1])}</p><button class="btn" data-close style="width:100%;margin-top:18px">Got it</button>`;modal.classList.add('show')};
function modeName(){return S.holiday.mode==='home'?'🏠 Holiday at Home':S.holiday.mode==='away'?'✈️ Holiday Away':'🎓 Normal Schedule'}
function helpButton(key){return `<button class="help-btn" data-help="${key}" aria-label="Explain">?</button>`}
function decorateTasks(){document.querySelectorAll('.task,.event').forEach(el=>{const taskId=el.dataset.edit||el.querySelector('[data-check]')?.dataset.check;const task=taskId?tasks().find(x=>x.id===taskId):null;if(task)el.dataset.cat=task.c})}
function findCardHeading(root,text){return [...root.querySelectorAll('h1,h2,h3')].find(x=>x.textContent.trim().toLowerCase().includes(text.toLowerCase()))}
function addHelpNear(root,text,key){const h=findCardHeading(root,text);if(h&&h.parentElement&&!h.parentElement.querySelector(`[data-help="${key}"]`)){const wrap=document.createElement('div');wrap.className='section-title';h.replaceWith(wrap);wrap.append(h);wrap.insertAdjacentHTML('beforeend',helpButton(key))}}
function todayProgress(){const d=day(),a=tasks().filter(x=>x.d===d&&!x.fixed),done=a.filter(x=>S.done[x.id]).length;return{done,total:a.length,pct:Math.round(done/Math.max(1,a.length)*100)}}
function nextCountdown(){return [...S.countdowns].map(c=>({...c,days:Math.max(0,Math.ceil((new Date(c.date)-Date.now())/86400000))})).sort((a,b)=>a.days-b.days)[0]}
function categoryStreak(cat){let n=0;const today=day();for(let k=0;k<7;k++){const d=(today-k+7)%7;if(tasks().some(x=>x.d===d&&x.c===cat&&S.done[x.id]))n++;else if(k>0)break}return n}
function enhanceHome(){const root=document.getElementById('home');if(!root)return;const hero=root.querySelector('.hero');if(hero&&!hero.querySelector('.mode-chip'))hero.insertAdjacentHTML('beforeend',`<div style="margin-top:13px"><span class="mode-chip">${modeName()}</span></div>`);if(!root.querySelector('#dailySummary71')){const p=todayProgress(),next=nextCountdown(),summary=document.createElement('div');summary.id='dailySummary71';summary.className='card';summary.style.marginTop='10px';summary.innerHTML=`<div class="dashboard-row"><div><span class="pill">TODAY</span><h2 style="margin-top:8px">${p.done} of ${p.total} quests complete</h2><p class="muted" style="margin-top:5px">Small wins count. Your schedule stays realistic.</p></div><div class="ring" style="--v:${p.pct}"><strong>${p.pct}%</strong></div></div><div class="mini-grid" style="margin-top:14px"><div class="mini-card"><span class="muted">Gym streak</span><strong>${categoryStreak('Gym')}🔥</strong></div><div class="mini-card"><span class="muted">Code streak</span><strong>${categoryStreak('Programming')}🔥</strong></div><div class="mini-card"><span class="muted">Next goal</span><strong>${next?next.emoji+' '+next.days+'d':'—'}</strong></div></div>`;const firstCard=root.querySelector('.card');if(firstCard)firstCard.insertAdjacentElement('beforebegin',summary);else hero?.insertAdjacentElement('afterend',summary)}addHelpNear(root,'Smart Planner','smart');addHelpNear(root,'Health','health');addHelpNear(root,'Streak','streaks');const smart=[...root.querySelectorAll('.card')].find(c=>c.textContent.includes('Smart Planner'));if(smart&&!smart.querySelector('.smart-reason'))smart.insertAdjacentHTML('beforeend','<div class="smart-reason"><b>Why this suggestion?</b><p class="muted" style="margin-top:4px">It fits before sleep and is based on the least-completed focus category this week.</p></div>')}
function enhancePlanner(){const root=document.getElementById('planner');if(!root)return;const hero=root.querySelector('.hero');if(hero&&!root.querySelector('#plannerSearch'))hero.insertAdjacentHTML('afterend','<div class="searchbar"><input id="plannerSearch" class="input" placeholder="Search tasks, places or categories"></div>');decorateTasks()}
function enhanceGoals(){const root=document.getElementById('goals');if(!root)return;addHelpNear(root,'Countdown','goals');addHelpNear(root,'Future','goals');addHelpNear(root,'Challenge','challenges');root.querySelectorAll('.card').forEach(c=>{if(c.textContent.includes('%')&&!c.classList.contains('goal-card'))c.classList.add('goal-card')})}
function enhanceProgress(){const root=document.getElementById('progress');if(!root)return;addHelpNear(root,'Progress photos','photos');addHelpNear(root,'Life stats','life');addHelpNear(root,'Weekly','stats');const grid=root.querySelector('.photoGrid');if(grid&&!grid.children.length)grid.outerHTML='<div class="empty">📸 No progress photos yet.<br><span style="font-size:13px">Add your first photo above and keep the lighting consistent.</span></div>';const chart=root.querySelector('.chart');if(chart&&!chart.nextElementSibling?.classList.contains('chart-labels'))chart.insertAdjacentHTML('afterend','<div class="chart-labels"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div>')}
function enhanceProfile(){const root=document.getElementById('profile');if(!root)return;addHelpNear(root,'Burnout','burnout');addHelpNear(root,'Holiday','holiday');addHelpNear(root,'XP','xp');if(!root.querySelector('#changelog71')){const c=document.createElement('div');c.id='changelog71';c.className='card';c.style.marginTop='10px';c.innerHTML='<div class="section-title"><h2>What’s new</h2><span class="pill">7.1</span></div><div class="changelog-item"><b>Clarity</b><p class="muted">Help buttons explain XP, health, burnout, goals, challenges and statistics.</p></div><div class="changelog-item"><b>Design</b><p class="muted">New dashboard, stronger hierarchy, category accents and larger iPhone tap targets.</p></div><div class="changelog-item"><b>Guidance</b><p class="muted">First-launch tour, empty states, comparison mode and clearer Smart Planner reasoning.</p></div><button class="btn secondary" data-action="restart-tour" style="width:100%;margin-top:10px">Replay guided tour</button>';root.append(c)}}
const originalRender=render;render=function(){originalRender();requestAnimationFrame(()=>{enhanceHome();enhancePlanner();enhanceGoals();enhanceProgress();enhanceProfile();decorateTasks()})};
function tour(){const el=document.getElementById('onboarding');if(!el)return;const slides=[['✨','Welcome to QuestWeek','Your schedule, long-term goals and progress now live in one clearer daily system.'],['◉','Home','See today’s progress, Smart Planner advice, streaks and your next countdown.'],['▦','Planner','Tap any task to edit it. Times automatically reorder, and conflicts remain visible.'],['★','Goals','Track editable countdowns, milestone checklists and long-term challenges.'],['▥','Progress','Store progress photos, review weekly statistics, Life Stats and your personal timeline.'],['⚙︎','Profile','Change Holiday Mode, school timetable, burnout inputs, backups and app guidance.']];let i=0;const done=()=>{S.ui.tourDone=true;save();el.classList.add('hidden');toast('QuestWeek is ready')};const paint=()=>{const [icon,title,body]=slides[i];el.innerHTML=`<div><div class="tour-icon">${icon}</div><span class="pill" style="margin-top:24px">STEP ${i+1} OF ${slides.length}</span><h1 style="font-size:36px;margin-top:14px">${title}</h1><p class="muted" style="font-size:18px;line-height:1.5;margin-top:12px">${body}</p></div><div><div class="tour-dots">${slides.map((_,n)=>`<i class="${n===i?'active':''}"></i>`).join('')}</div><div class="row" style="margin-top:24px"><button class="btn secondary" id="tourSkip">Skip</button><button class="btn" id="tourNext">${i===slides.length-1?'Start QuestWeek':'Continue'}</button></div></div>`;el.querySelector('#tourSkip').onclick=done;el.querySelector('#tourNext').onclick=()=>{if(i<slides.length-1){i++;paint()}else done()}};el.classList.remove('hidden');paint()}
document.addEventListener('input',ev=>{if(ev.target.id==='plannerSearch'){const q=ev.target.value.toLowerCase();document.querySelectorAll('#planner .event').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'':'none')}});
document.addEventListener('click',ev=>{const h=ev.target.closest('[data-help]');if(h){ev.preventDefault();ev.stopPropagation();help(h.dataset.help);return}const a=ev.target.closest('[data-action="restart-tour"]');if(a){S.ui.tourDone=false;save();tour();return}const img=ev.target.closest('.photoGrid img');if(img){const src=img.src;let arr=S.ui.photoCompare||[];arr=arr.includes(src)?arr.filter(x=>x!==src):[...arr,src].slice(-2);S.ui.photoCompare=arr;save();document.querySelectorAll('.photoGrid img').forEach(x=>x.classList.toggle('selected',arr.includes(x.src)));if(arr.length===2){sheet.innerHTML=`<button class="close-x" data-close>×</button><span class="pill">PHOTO COMPARISON</span><h2 style="margin-top:10px">Compare progress</h2><div class="compare-grid" style="margin-top:14px"><img src="${arr[0]}"><img src="${arr[1]}"></div><button class="btn" data-close style="width:100%;margin-top:14px">Done</button>`;modal.classList.add('show')}return}const button=ev.target.closest('.btn,.check,[data-action]');if(button&&!button.matches('[data-close]')){button.classList.add('pulse');setTimeout(()=>button.classList.remove('pulse'),280)}});
const observer=new MutationObserver(()=>decorateTasks());observer.observe(document.body,{childList:true,subtree:true});
render();if(!S.ui.tourDone)setTimeout(tour,250);else if(S.ui.lastVersion!=='7.1'){S.ui.lastVersion='7.1';save();setTimeout(()=>toast('QuestWeek 7.1 design update loaded'),500)}
})();