(()=>{'use strict';
if(typeof S==='undefined'||typeof render!=='function'||typeof tasks!=='function')return;
const esc=s=>String(s??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const dur=x=>Math.max(0,mn(x.end)-mn(x.start));
const dayKey=()=>dateKey(new Date());
S.v66=Object.assign({weeklyXpGoal:3000,reviews:{},timeline:[],unlocked:{},goalSteps:{},graphs:{weight:[],money:[],xp:[]}},S.v66||{});
if(!S.v66.timeline.length)S.v66.timeline.push({id:'built',date:'2026',title:'Built QuestWeek',emoji:'🛠️'});
const categories={Fitness:['Gym','Badminton','Boxing','Endurance','Calisthenics'],Learning:['Study','Programming','Japanese','Chess'],Money:['Income','Work'],Health:['Meditation','Stretching','Meal','Sleep'],Adventure:['Personal']};
function weekXp(){return tasks().reduce((n,x)=>n+(S.done[x.id]?(x.xp??XP[x.c]??0):0),0)+(Object.values(S.water||{}).filter(v=>v>=2500).length*20)}
function hoursByCat(){const out={};tasks().forEach(x=>{if(S.done[x.id]&&dur(x)>0)out[x.c]=(out[x.c]||0)+dur(x)});return out}
function streak(cat){let n=0;for(let d=di();d>=0;d--){const q=tasks().filter(x=>x.d===d&&x.c===cat&&!x.fixed);if(!q.length)continue;if(q.some(x=>S.done[x.id]))n++;else break}return n}
function achievements(){const h=hoursByCat(),xp=weekXp(),completed=Object.values(S.done||{}).filter(Boolean).length;return[
{id:'first',emoji:'🌱',name:'First Quest',ok:completed>=1},
{id:'xp1k',emoji:'⚡',name:'1,000 Weekly XP',ok:xp>=1000},
{id:'gym10',emoji:'🏋️',name:'10 Fitness Sessions',ok:tasks().filter(x=>S.done[x.id]&&categories.Fitness.includes(x.c)).length>=10},
{id:'code5',emoji:'💻',name:'5 Hours Programming',ok:(h.Programming||0)>=300},
{id:'study5',emoji:'📚',name:'5 Hours Studying',ok:(h.Study||0)>=300},
{id:'water7',emoji:'💧',name:'Hydrated Week',ok:Object.values(S.water||{}).filter(v=>v>=2500).length>=7},
{id:'money10',emoji:'💰',name:'10,000 DKK',ok:Number(S.money||0)>=10000},
{id:'challenge',emoji:'🏆',name:'Challenge Complete',ok:(S.challenges||[]).some(c=>c.value>=c.target)}]}
function unlock(){for(const a of achievements())if(a.ok&&!S.v66.unlocked[a.id]){S.v66.unlocked[a.id]=new Date().toISOString();S.v66.timeline.unshift({id:'ach-'+a.id,date:new Date().toLocaleDateString('en-DK'),title:a.name,emoji:a.emoji});setTimeout(()=>alert(`🎉 Achievement unlocked: ${a.name}`),50)}save()}
function goalSteps(g){if(!S.v66.goalSteps[g.id])S.v66.goalSteps[g.id]=g.name.toLowerCase().includes('japan')?['Improve Japanese','Save money','Find ski resort work','Visa and paperwork','Book travel']:g.name.toLowerCase().includes('cyber')?['Linux','Networking','Python','Web security','CTFs / portfolio']:g.name.toLowerCase().includes('everest')?['Build endurance','Hiking experience','Mountaineering course','Alpine climbs','Expedition planning']:['Define next milestone','Complete preparation','Review progress'];return S.v66.goalSteps[g.id]}
function smartCoach(){const A=tasks(),h=hoursByCat(),d=di(),today=A.filter(x=>x.d===d),free=today.filter(x=>/free time/i.test(x.t||'')).reduce((n,x)=>n+dur(x),0);const options=[['Programming',h.Programming||0,'programming'],['Study',h.Study||0,'studying'],['Income',h.Income||0,'side hustle']].sort((a,b)=>a[1]-b[1]);const pick=options[0];if(burnout()==='High')return['Recovery first','Your burnout risk is high. Keep extra time free or choose an easy walk and mobility.'];if(free>=90)return[`Opportunity: ${pick[2]}`,`You have at least ${Math.round(free/60)} hours marked as free today, and ${pick[2]} is currently your least-completed focus area.`];return['Stay with the plan','Your day is already structured. Finishing the planned tasks is more valuable than adding more.']}
function miniBars(data,max){return data.map(x=>`<div style="display:grid;grid-template-columns:90px 1fr 55px;gap:8px;align-items:center;margin:9px 0"><span class="muted">${esc(x[0])}</span><div class="bar"><span style="width:${Math.min(100,max?x[1]/max*100:0)}%"></span></div><b style="text-align:right">${esc(x[2])}</b></div>`).join('')}
const baseRender=render;
render=function(){baseRender();
 document.querySelectorAll('#startFocus,.focus').forEach(e=>e.remove());
 unlock();
 const xp=weekXp(),goal=Number(S.v66.weeklyXpGoal||3000),h=hoursByCat(),coach=smartCoach();
 const homeRoot=document.getElementById('home');
 if(homeRoot){const card=document.createElement('div');card.className='card';card.style.marginTop='10px';card.innerHTML=`<span class="pill">WEEKLY PROGRESS</span><div class="countdown" style="margin-top:9px"><div><h2>${xp.toLocaleString('en-DK')} / ${goal.toLocaleString('en-DK')} XP</h2><p class="muted">${Math.min(100,Math.round(xp/Math.max(1,goal)*100))}% of weekly goal</p></div><strong>${Math.max(0,goal-xp).toLocaleString('en-DK')} left</strong></div><div class="bar"><span style="width:${Math.min(100,xp/Math.max(1,goal)*100)}%"></span></div><h3 style="margin-top:16px">💡 ${esc(coach[0])}</h3><p class="muted" style="margin-top:5px">${esc(coach[1])}</p>`;const first=homeRoot.querySelector('.card');if(first)first.insertAdjacentElement('afterend',card);else homeRoot.prepend(card)}
 const progressRoot=document.getElementById('progress');
 if(progressRoot){
  const stats=document.createElement('div');stats.innerHTML=`<div class="card" style="margin-top:10px"><h2>Streaks</h2>${miniBars([['Gym',streak('Gym'),streak('Gym')+' days'],['Programming',streak('Programming'),streak('Programming')+' days'],['Study',streak('Study'),streak('Study')+' days'],['Japanese',streak('Japanese'),streak('Japanese')+' days'],['Water',Object.values(S.water||{}).filter(v=>v>=2500).length,Object.values(S.water||{}).filter(v=>v>=2500).length+' days']],7)}</div><div class="card" style="margin-top:10px"><h2>Time this week</h2>${miniBars(Object.entries(h).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>[k,v,`${Math.floor(v/60)}h ${v%60}m`]),Math.max(1,...Object.values(h)))||'<p class="muted">Complete timed tasks to build your statistics.</p>'}</div><div class="card" style="margin-top:10px"><h2>Achievements</h2>${achievements().map(a=>`<div class="task" style="grid-template-columns:44px 1fr"><div class="ico">${a.emoji}</div><div><div class="title">${esc(a.name)}</div><div class="meta">${a.ok?'Unlocked':'Locked'}</div></div></div>`).join('')}</div><div class="card" style="margin-top:10px"><h2>Weekly activity graph</h2>${miniBars(D.map((day,d)=>{const v=tasks().filter(x=>x.d===d&&S.done[x.id]).reduce((n,x)=>n+(x.xp??XP[x.c]??0),0);return[day.slice(0,3),v,String(v)]}),Math.max(1,...D.map((_,d)=>tasks().filter(x=>x.d===d&&S.done[x.id]).reduce((n,x)=>n+(x.xp??XP[x.c]??0),0))))}</div>`;
  progressRoot.appendChild(stats)
 }
 const goalsRoot=document.getElementById('goals');
 if(goalsRoot){const map=document.createElement('div');map.innerHTML=`<div class="head"><h2>Life Map</h2></div>${Object.entries(categories).map(([name,cats])=>{const qs=tasks().filter(x=>cats.includes(x.c)&&!x.fixed),done=qs.filter(x=>S.done[x.id]).length,p=Math.round(done/Math.max(1,qs.length)*100);return`<div class="card" style="margin-bottom:10px"><div class="countdown"><h3>${name}</h3><b>${p}%</b></div><div class="bar"><span style="width:${p}%"></span></div></div>`}).join('')}<div class="head"><h2>Goal milestones</h2></div>${(S.goals||[]).map(g=>`<div class="card" style="margin-bottom:10px"><h3>${esc(g.name)}</h3>${goalSteps(g).map((s,i)=>{const k=`${g.id}:${i}`,on=!!S.milestones[k];return`<label style="display:flex;gap:9px;margin-top:9px"><input type="checkbox" data-goalstep="${esc(k)}" ${on?'checked':''}><span>${esc(s)}</span></label>`}).join('')}</div>`).join('')}`;goalsRoot.appendChild(map);map.querySelectorAll('[data-goalstep]').forEach(x=>x.onchange=()=>{S.milestones[x.dataset.goalstep]=x.checked;save();render()})}
 const moreRoot=document.getElementById('more');
 if(moreRoot){const extra=document.createElement('div');const r=S.v66.reviews[dayKey()]||{};extra.innerHTML=`<div class="card" style="margin-top:10px"><h2>Weekly XP goal</h2><input id="weeklyXpGoal66" class="input" type="number" min="100" step="100" value="${goal}"><button id="saveXpGoal66" class="btn" style="width:100%;margin-top:8px">Save goal</button></div><div class="card" style="margin-top:10px"><h2>Evening review</h2><textarea id="reviewWin66" class="input" style="margin-top:8px;min-height:70px" placeholder="What went well?">${esc(r.win||'')}</textarea><textarea id="reviewImprove66" class="input" style="margin-top:8px;min-height:70px" placeholder="What should improve?">${esc(r.improve||'')}</textarea><div class="row" style="margin-top:8px"><label class="muted">Mood 1–10<input id="reviewMood66" class="input" type="number" min="1" max="10" value="${r.mood||7}"></label><label class="muted">Energy 1–10<input id="reviewEnergy66" class="input" type="number" min="1" max="10" value="${r.energy||7}"></label></div><button id="saveReview66" class="btn" style="width:100%;margin-top:8px">Save review</button></div><div class="card" style="margin-top:10px"><h2>Life Timeline</h2>${S.v66.timeline.slice(0,20).map(e=>`<div style="padding:9px 0;border-bottom:1px solid var(--line)"><b>${esc(e.emoji)} ${esc(e.title)}</b><div class="muted">${esc(e.date)}</div></div>`).join('')}<div class="row" style="margin-top:10px"><input id="timelineTitle66" class="input" placeholder="Life event"><input id="timelineDate66" class="input" placeholder="Date / year"></div><button id="addTimeline66" class="btn" style="width:100%;margin-top:8px">Add life event</button></div>`;moreRoot.appendChild(extra);extra.querySelector('#saveXpGoal66').onclick=()=>{S.v66.weeklyXpGoal=Math.max(100,Number(extra.querySelector('#weeklyXpGoal66').value||3000));save();render()};extra.querySelector('#saveReview66').onclick=()=>{S.v66.reviews[dayKey()]={win:extra.querySelector('#reviewWin66').value,improve:extra.querySelector('#reviewImprove66').value,mood:Number(extra.querySelector('#reviewMood66').value),energy:Number(extra.querySelector('#reviewEnergy66').value)};save();alert('Evening review saved.')};extra.querySelector('#addTimeline66').onclick=()=>{const t=extra.querySelector('#timelineTitle66').value.trim();if(!t)return;S.v66.timeline.unshift({id:'life-'+uid(),date:extra.querySelector('#timelineDate66').value.trim()||new Date().toLocaleDateString('en-DK'),title:t,emoji:'⭐'});save();render()}}
};
render();
})();